# Generated by Django 6.0.4 on 2026-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mode', models.CharField(choices=[('upload', 'Upload'), ('live', 'Live'), ('sample', 'Sample')], max_length=16)),
                ('predicted_emotion', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('model_version', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='predictions/%Y/%m/%d/')),
                ('image_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('raw_scores', models.JSONField(blank=True, default=dict)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
